# Generated by Django 5.2.17 on 2026-10-04 03:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('municipio_ibge', models.PositiveIntegerField(choices=[(3503208, 'Araraquara (SP)')], verbose_name='município')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('ponto', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='localização')),
                ('tem_bebedouro', models.BooleanField(blank=True, null=True, verbose_name='tem bebedouro')),
                ('tem_sanitario', models.BooleanField(blank=True, null=True, verbose_name='tem sanitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('barra_fixa', 'Barra fixa'), ('barras_paralelas', 'Barras paralelas'), ('espaldar', 'Espaldar'), ('barra_australiana', 'Barra australiana'), ('outro', 'Outro')], max_length=20)),
                ('nome_outro', models.CharField(blank=True, max_length=60, verbose_name='nome (tipo outro)')),
                ('altura_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='altura (cm)')),
                ('largura_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='largura (cm)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='locais.local')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_horario', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=5, verbose_name='faixa de horário')),
                ('iluminacao', models.CharField(blank=True, choices=[('boa', 'Boa'), ('fraca', 'Fraca'), ('ausente', 'Ausente')], max_length=7, verbose_name='iluminação')),
                ('movimento', models.CharField(choices=[('movimentado', 'Movimentado'), ('pouco_movimento', 'Pouco movimento'), ('vazio', 'Vazio')], max_length=15)),
                ('limpeza', models.CharField(choices=[('limpo', 'Limpo'), ('regular', 'Regular'), ('sujo', 'Sujo')], max_length=7)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_local', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='locais.local')),
            ],
            options={
                'verbose_name': 'avaliação do local',
                'verbose_name_plural': 'avaliações do local',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(choices=[('bom', 'Bom'), ('desgastado', 'Desgastado'), ('precario', 'Precário'), ('quebrado', 'Quebrado')], max_length=12, verbose_name='condição')),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_condicao', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_condicao', to='locais.equipamento')),
            ],
            options={
                'verbose_name': 'registro de condição',
                'verbose_name_plural': 'registros de condição',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='local',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('municipio_ibge'), name='local_nome_unico_por_municipio'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'outro'), models.Q(('nome_outro', ''), _negated=True)), models.Q(models.Q(('tipo', 'outro'), _negated=True), ('nome_outro', '')), _connector='OR'), name='equipamento_nome_outro_somente_tipo_outro'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.CheckConstraint(condition=models.Q(('largura_cm__isnull', True), ('tipo', 'barras_paralelas'), _connector='OR'), name='equipamento_largura_somente_paralelas'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.CheckConstraint(condition=models.Q(('altura_cm__isnull', True), ('altura_cm__gt', 0), _connector='OR'), name='equipamento_altura_positiva'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.CheckConstraint(condition=models.Q(('largura_cm__isnull', True), ('largura_cm__gt', 0), _connector='OR'), name='equipamento_largura_positiva'),
        ),
        migrations.AddIndex(
            model_name='avaliacaolocal',
            index=models.Index(fields=['local', 'faixa_horario', '-registrado_em'], name='avaliacao_local_faixa_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaolocal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('faixa_horario', 'noite'), _negated=True), models.Q(('iluminacao', ''), _negated=True), _connector='OR'), name='avaliacao_iluminacao_obrigatoria_noite'),
        ),
        migrations.AddIndex(
            model_name='registrocondicao',
            index=models.Index(fields=['equipamento', '-registrado_em'], name='registro_cond_equip_data_idx'),
        ),
    ]
