# Generated by Django 5.2.17 on 2026-10-04 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('local_inexistente', 'Local não existe'), ('local_duplicado', 'Local duplicado'), ('equipamento_incorreto', 'Equipamento incorreto'), ('avaliacao_incorreta', 'Avaliação incorreta'), ('foto_inadequada', 'Foto inadequada')], max_length=21)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente')], default='aberta', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='locais.local')),
            ],
            options={
                'verbose_name': 'denúncia',
                'verbose_name_plural': 'denúncias',
                'ordering': ['-criada_em'],
            },
        ),
    ]
